/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorySlugIndexRouteImport } from './routes/$categorySlug.index'
import { Route as TraCuuToolSlugRouteImport } from './routes/tra-cuu.$toolSlug'
import { Route as TraCuuKetQuaIdRouteImport } from './routes/tra-cuu-ket-qua.$id'
import { Route as ThanSoHocBaoCaoRouteImport } from './routes/than-so-hoc.bao-cao'
import { Route as LamBaiSlugRouteImport } from './routes/lam-bai.$slug'
import { Route as KetQuaIdRouteImport } from './routes/ket-qua.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugIndexRoute = CategorySlugIndexRouteImport.update({
  id: '/$categorySlug/',
  path: '/$categorySlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraCuuToolSlugRoute = TraCuuToolSlugRouteImport.update({
  id: '/tra-cuu/$toolSlug',
  path: '/tra-cuu/$toolSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TraCuuKetQuaIdRoute = TraCuuKetQuaIdRouteImport.update({
  id: '/tra-cuu-ket-qua/$id',
  path: '/tra-cuu-ket-qua/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanSoHocBaoCaoRoute = ThanSoHocBaoCaoRouteImport.update({
  id: '/than-so-hoc/bao-cao',
  path: '/than-so-hoc/bao-cao',
  getParentRoute: () => rootRouteImport,
} as any)
const LamBaiSlugRoute = LamBaiSlugRouteImport.update({
  id: '/lam-bai/$slug',
  path: '/lam-bai/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KetQuaIdRoute = KetQuaIdRouteImport.update({
  id: '/ket-qua/$id',
  path: '/ket-qua/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ket-qua/$id': typeof KetQuaIdRoute
  '/lam-bai/$slug': typeof LamBaiSlugRoute
  '/than-so-hoc/bao-cao': typeof ThanSoHocBaoCaoRoute
  '/tra-cuu-ket-qua/$id': typeof TraCuuKetQuaIdRoute
  '/tra-cuu/$toolSlug': typeof TraCuuToolSlugRoute
  '/$categorySlug/': typeof CategorySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ket-qua/$id': typeof KetQuaIdRoute
  '/lam-bai/$slug': typeof LamBaiSlugRoute
  '/than-so-hoc/bao-cao': typeof ThanSoHocBaoCaoRoute
  '/tra-cuu-ket-qua/$id': typeof TraCuuKetQuaIdRoute
  '/tra-cuu/$toolSlug': typeof TraCuuToolSlugRoute
  '/$categorySlug': typeof CategorySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ket-qua/$id': typeof KetQuaIdRoute
  '/lam-bai/$slug': typeof LamBaiSlugRoute
  '/than-so-hoc/bao-cao': typeof ThanSoHocBaoCaoRoute
  '/tra-cuu-ket-qua/$id': typeof TraCuuKetQuaIdRoute
  '/tra-cuu/$toolSlug': typeof TraCuuToolSlugRoute
  '/$categorySlug/': typeof CategorySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ket-qua/$id'
    | '/lam-bai/$slug'
    | '/than-so-hoc/bao-cao'
    | '/tra-cuu-ket-qua/$id'
    | '/tra-cuu/$toolSlug'
    | '/$categorySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ket-qua/$id'
    | '/lam-bai/$slug'
    | '/than-so-hoc/bao-cao'
    | '/tra-cuu-ket-qua/$id'
    | '/tra-cuu/$toolSlug'
    | '/$categorySlug'
  id:
    | '__root__'
    | '/'
    | '/ket-qua/$id'
    | '/lam-bai/$slug'
    | '/than-so-hoc/bao-cao'
    | '/tra-cuu-ket-qua/$id'
    | '/tra-cuu/$toolSlug'
    | '/$categorySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KetQuaIdRoute: typeof KetQuaIdRoute
  LamBaiSlugRoute: typeof LamBaiSlugRoute
  ThanSoHocBaoCaoRoute: typeof ThanSoHocBaoCaoRoute
  TraCuuKetQuaIdRoute: typeof TraCuuKetQuaIdRoute
  TraCuuToolSlugRoute: typeof TraCuuToolSlugRoute
  CategorySlugIndexRoute: typeof CategorySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categorySlug/': {
      id: '/$categorySlug/'
      path: '/$categorySlug'
      fullPath: '/$categorySlug/'
      preLoaderRoute: typeof CategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tra-cuu/$toolSlug': {
      id: '/tra-cuu/$toolSlug'
      path: '/tra-cuu/$toolSlug'
      fullPath: '/tra-cuu/$toolSlug'
      preLoaderRoute: typeof TraCuuToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tra-cuu-ket-qua/$id': {
      id: '/tra-cuu-ket-qua/$id'
      path: '/tra-cuu-ket-qua/$id'
      fullPath: '/tra-cuu-ket-qua/$id'
      preLoaderRoute: typeof TraCuuKetQuaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/than-so-hoc/bao-cao': {
      id: '/than-so-hoc/bao-cao'
      path: '/than-so-hoc/bao-cao'
      fullPath: '/than-so-hoc/bao-cao'
      preLoaderRoute: typeof ThanSoHocBaoCaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lam-bai/$slug': {
      id: '/lam-bai/$slug'
      path: '/lam-bai/$slug'
      fullPath: '/lam-bai/$slug'
      preLoaderRoute: typeof LamBaiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ket-qua/$id': {
      id: '/ket-qua/$id'
      path: '/ket-qua/$id'
      fullPath: '/ket-qua/$id'
      preLoaderRoute: typeof KetQuaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KetQuaIdRoute: KetQuaIdRoute,
  LamBaiSlugRoute: LamBaiSlugRoute,
  ThanSoHocBaoCaoRoute: ThanSoHocBaoCaoRoute,
  TraCuuKetQuaIdRoute: TraCuuKetQuaIdRoute,
  TraCuuToolSlugRoute: TraCuuToolSlugRoute,
  CategorySlugIndexRoute: CategorySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
